### PR TITLE
MIME4J-313 -- allow for builds with JDK > 8 but target/release of 8

### PR DESCRIPTION
**Pull request by tballison**

### CODE REVIEW

**Comment by tballison** [comment]
This prevents the need for https://github.com/apache/james-mime4j/pull/62

**Comment by tballison** [comment]
FTR (separate issue): I'm getting the same build failures when I try to build with Java 8 as: https://github.com/apache/james-mime4j/pull/62#issuecomment-961186013

**Review by chibenwa — APPROVED** [review]
Thanks!

**Review by Arsnael — APPROVED** [review]
Thanks for this!

**Comment by tballison** [comment]
I just noticed that 0.8.7 was released without this.  We can't upgrade in Tika until this is fixed.  @chibenwa, any chance someone can hit the magical merge button?

**Comment by chibenwa** [comment]
Sorry this completly went off my radar...

**Comment by tballison** [comment]
Been there.  No problem at all.  THANK YOU!

**Pull request merged**
