### PR TITLE
MIME4J-310 Force using Buffer.flip

### PR DESCRIPTION
**Pull request by chibenwa**
ByteBuffer.flip is only implemented from JDK11 onward. Please note that issue
arise when compiling with a JDK 11 and running with a JDK 8 despite maven
target and sources releases.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by kevindorff** [comment]
Question... Trying to build locally per your request. Using JDK8 or JDK11 I get the same results.

Even for **master branch**, if I `mvn clean install` the build fails 21 tests in `core` and halts. Looking over BUILDING.txt and README.adoc I don't feel like I'm missing anything. My Maven is somewhat newer than you specify (3.6) but I don't feel like the error is related to the version of Maven or the JDK.

See the full build log and such here: https://gist.github.com/kevindorff/41e73500df4ca72175b7534123908462

**Comment by chibenwa** [comment]
> Are these failed tests

No, not that I am aware of...

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache James :: Mime4j :: Project 0.8.7-SNAPSHOT:
[INFO] 
[INFO] Apache James :: Mime4j :: Project .................. SUCCESS [  1.941 s]
[INFO] Apache James :: Mime4j :: Core ..................... SUCCESS [  4.172 s]
[INFO] Apache James :: Mime4j :: DOM ...................... SUCCESS [  6.203 s]
[INFO] Apache James :: Mime4j :: Storage .................. SUCCESS [  1.129 s]
[INFO] Apache James :: Mime4j :: Benchmarks ............... SUCCESS [  0.215 s]
[INFO] Apache James :: Mime4j :: Mbox Iterator ............ SUCCESS [  3.927 s]
[INFO] Apache James :: Mime4j :: Code Examples ............ SUCCESS [  0.293 s]
[INFO] Apache James :: Mime4j :: Assembly ................. SUCCESS [  0.873 s]
[INFO] Apache James :: Mime4j :: James utils .............. SUCCESS [  1.121 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.836 s
[INFO] Finished at: 2021-11-03T08:04:49+07:00
[INFO] ------------------------------------------------------------------------
````

**Comment by kevindorff** [comment]
@chibenwa Interesting. Are there further setup requirements that I might be missing?  Building under both Windows and WSL with Ubuntu failed. I then tried a cleaner approach

* a new VM with Ubuntu 20.04.3 LTS 
* Zulu OpenJDK JDK 1.8.0_312 
* Maven 3.8.3
* fresh `master` checkout of james-mime4j from git

`mvn clean install` gives me yet a different failing results. 

image

**Comment by chibenwa** [comment]
Looks like https://stackoverflow.com/questions/56255020/zoneddatetime-change-behavior-jdk-8-11 to me...

**Comment by chibenwa** [comment]
@kevindorff can you retest?

**Comment by kevindorff** [comment]
Using my Ubuntu VM, I checked out your PR and did a build. It still fails in I believe the same way in DOM.
https://gist.github.com/kevindorff/72c7445f49e39fcdc763cc924ff62105

I made a new Windows 11 VM, installed Zulu OpenJDK8 and Maven 3.8.3. No other changes. I checked out the PR. Fails in the same way I mentioned a few days ago in Core (I was testing on `master` at that time). This seems to be some default Windows configuration incompatibility. This is how it failed on my Windows dev box as well as under WSL Ubuntu 18.x on my machine.
https://gist.github.com/kevindorff/0fb02710c3b2ff7913e65ebaa53a732f

**Comment by chibenwa** [comment]
My bad, corrected and run on:

```
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

**Comment by kevindorff** [comment]
With the new commit

Using a Debian Linux machine (up to date), I checked out your PR and did a build. It passes now.

On my clean Windows 11 VM, installed Zulu OpenJDK8 and Maven 3.8.3. No other changes. I checked out the PR. **Fails on CORE as described above.**

**Comment by chibenwa** [comment]
Can you share the value of `System.getProperty("java.version");`

**Comment by kevindorff** [comment]
Using Groovy 3.0.9 and the script

```
for (key in System.properties.keySet().sort()) {
    printf('%-30s   %s\n', key, System.properties[key])
}
```

Has an output of

```
awt.toolkit                      sun.awt.windows.WToolkit
file.encoding                    Cp1252
file.encoding.pkg                sun.io
file.separator                   \
groovy.home                      c:\java\groovy-3.0.9
groovy.starter.conf              c:\java\groovy-3.0.9\conf\groovy-starter.conf
java.awt.graphicsenv             sun.awt.Win32GraphicsEnvironment
java.awt.printerjob              sun.awt.windows.WPrinterJob
java.class.path                  c:\java\groovy-3.0.9\lib\groovy-3.0.9.jar
java.class.version               52.0
java.endorsed.dirs               c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\endorsed
java.ext.dirs                    c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.home                        c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre
java.io.tmpdir                   C:\Users\User\AppData\Local\Temp\
java.library.path                c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\bin;c:\java\apache-maven-3.8.3\bin;c:\java\groovy-3.0.9\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\User\.dotnet\tools;C:\Program Files (x86)\GitHub CLI\;.
java.runtime.name                OpenJDK Runtime Environment
java.runtime.version             1.8.0_312-b07
java.specification.name          Java Platform API Specification
java.specification.vendor        Oracle Corporation
java.specification.version       1.8
java.vendor                      Azul Systems, Inc.
java.vendor.url                  http://www.azul.com/
java.vendor.url.bug              http://www.azul.com/support/
java.version                     1.8.0_312
java.vm.info                     mixed mode
java.vm.name                     OpenJDK 64-Bit Server VM
java.vm.specification.name       Java Virtual Machine Specification
java.vm.specification.vendor     Oracle Corporation
java.vm.specification.version    1.8
java.vm.vendor                   Azul Systems, Inc.
java.vm.version                  25.312-b07
jdk.vendor.version               Zulu 8.58.0.13-CA-win64
jline.terminal                   none
line.separator                   

os.arch                          amd64
os.name                          Windows 10
os.version                       10.0
path.separator                   ;
program.name                     
script.name                      C:\Users\User\save\listProperties.groovy
sun.arch.data.model              64
sun.boot.class.path              c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\resources.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\rt.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\sunrsasign.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\jsse.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\jce.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\charsets.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\lib\jfr.jar;c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\classes
sun.boot.library.path            c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\jre\bin
sun.cpu.endian                   little
sun.cpu.isalist                  amd64
sun.desktop                      windows
sun.io.unicode.encoding          UnicodeLittle
sun.java.command                 org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf c:\java\groovy-3.0.9\conf\groovy-starter.conf --classpath . .\listProperties.groovy
sun.java.launcher                SUN_STANDARD
sun.jnu.encoding                 Cp1252
sun.management.compiler          HotSpot 64-Bit Tiered Compilers
sun.os.patch.level               
sun.stderr.encoding              cp437
tools.jar                        c:\java\zulu8.58.0.13-ca-jdk8.0.312-win_x64\lib\tools.jar
user.country                     US
user.dir                         C:\Users\User\save
user.home                        C:\Users\User
user.language                    en
user.name                        User
user.script                      
user.timezone                    
user.variant                     
```

**Comment by chibenwa** [comment]
See https://github.com/apache/james-mime4j/pull/67

**Pull request closed without merging**
