### PR TITLE
Mime4 j 252

### PR DESCRIPTION
**Pull request by chibenwa**
Required by https://github.com/linagora/james-project/pull/425

### CODE REVIEW

**Comment by mbaechler** [comment]
you don't need to tag a release ?

**Comment by chibenwa** [comment]
http://www.apache.org/dev/publishing-maven-artifacts.html#close-stage

**Staging a release**
1 - Prepare your POMs for release

>   Make sure there are no dependencies on snapshots in the POMs to be released. However, the project you want to stage must be a SNAPSHOT version.

**Comment by chibenwa** [comment]
Oh you meant git tag ? Sorry...

**Comment by mbaechler** [comment]
No I mean giving it a real version, but if it's not the way it works, just do a git tag, yes

**Pull request merged**
