### PR TITLE
MIME4J-273 Add limit and position to LimitedInputStream exception mes…

### PR DESCRIPTION
**Pull request by chibenwa**
…sage

### CODE REVIEW

**Comment by ieugen** [comment]
Test for the exception message?
Is that a thing we should test?

**Comment by mbaechler** [comment]
> Test for the exception message?
> Is that a thing we should test?

I don't see any reason not to. You don't need to match the exact message but checking that:
* adding some information to the message doesn't break our ability to throw this exception
* the information actually contain what we think it does

... well ... it's about not doing blind change

**Comment by chibenwa** [comment]
> No test?

Sorry I'm short of time to contribute such specific tests. That's long fileds, there should be no issue affecting throwing. And I am not pro-efficient in that part of the code base, I just want a quick win debugging insight on some issues that happens in production to be a bit less blind (I know a limit is reached but I don't know which one)

**Comment by mbaechler** [comment]
I don't understand, is it ok to the community to just arbitrarily merge stuff without tests?

**Comment by chibenwa** [comment]
> I don't understand, is it ok to the community to just arbitrarily merge stuff without tests?

That is just an error message.

I don't even know which test to write.

**Comment by mbaechler** [comment]
> > I don't understand, is it ok to the community to just arbitrarily merge stuff without tests?
> 
> That is just an error message.

You already said it, I already answered

> I don't even know which test to write.

It's not described here : https://github.com/apache/james-mime4j/pull/32#issuecomment-654104412 ?

**Pull request merged**
