### PR TITLE
Fix some warnings reported by intelliJ

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by jochenw — APPROVED** [review]
To me, this looks generally good. That said, I won't pull it in. 20 files in a single PR is **way** too much!

**Comment by chibenwa** [comment]
> 20 files in a single PR is way too much!

Yet the overall changeset is very limited (+27 / -76)... Don't in counter-balance?

All commits are rather small...

**Comment by chibenwa** [comment]
IntelliJ fails to understand which JJT code actually is going to be used, I dropped the incriminated commit.

Build :green_apple: locally.

It could be good to consider having a **JenkinsFile** for this repository too....

**Review by Arsnael — APPROVED** [review]

**Review by mbaechler — APPROVED** [review]

**Comment by mbaechler** [comment]
> To me, this looks generally good. That said, I won't pull it in. 20 files in a single PR is **way** too much!

I agree with @chibenwa , the number of file is not a good enough metric by itself, so changeset is small and the risk is really low.

**Pull request merged**
