### PR TITLE
MIME4J-279 Fixed JavaDoc errors to comply with Java8.

### PR DESCRIPTION
**Pull request by dmak**

### CODE REVIEW

**Comment by chibenwa** [comment]
Hi,

This pull request has just been merged.

Thank you again for your dedication toward the James project. 

One very last thing: I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Thanks again,

Cheers,

Benoit

**Comment by sideeffffect** [comment]
Will a version with this patch be published soon?
Because the most recent version of `mime4j` (`0.8.5`) still doesn't contain JavaDoc:
 * https://repo1.maven.org/maven2/org/apache/james/apache-mime4j//
 * https://repo1.maven.org/maven2/org/apache/james/apache-mime4j-core/0.8.5/

**Comment by chibenwa** [comment]
Hello, 

I had a quick look. This patch is merged and most recent releases to ship it.

However, I would say that javadoc might not be produced because the `maven-javadoc-plugin` is missing?

Would you like to contribute it?

Cheers,

Benoit

**Comment by sideeffffect** [comment]
I'll give it a try :wink: 
https://github.com/apache/james-mime4j/pull/54

**Pull request closed without merging**
