### PR TITLE
MIME4J-273 Fix encoded word splitting point for EncodeQ method as well.

### PR DESCRIPTION
**Pull request by bwndai**

### CODE REVIEW

**Comment by chibenwa** [comment]
Please do use the JIRA number as a prefix of your commit.

This intends to makes code searching easier.

Example: 

```
MIME4J-273 Fix encoded word splitting point for EncodeQ method as well.
```

**Comment by bwndai** [comment]
Yes, I do think we need to reschedule a vote, and include this fix.

Thanks.
Bowen

**Comment by chibenwa** [comment]
Hi,

You have a compilation failure on this PR (missing `;`).

Once fixed, there is a test failure...

```
Failed tests: 
  FieldsTest.testSubject:256 expected:<...45678901234567890123[4?=
 =?US-ASCII?Q?]56789012345678901234...> but was:<...45678901234567890123[?=
 =?US-ASCII?Q?4]56789012345678901234...>
```

Could you update this pull request?

You can run test easily from the command line: `mvn clean install` in the base project.

Cheers,

Benoit Tellier

**Comment by bwndai** [comment]
I have fixed the failing tests and have verified that the tests are passing.

**Comment by commitcheck** [comment]
hi @chibenwa, I noticed your comment about using a JIRA number as a prefix. I built an app to automate this. CommitCheck runs a regex to check that each commit contains a JIRA number in the right format. Hopefully this will help save time on code reviews. It's free for OSS projects -> https://github.com/apps/commitcheck-app. Let me know if you have any questions :)

**Comment by chibenwa** [comment]
Hi,

This pull request has just been merged.

Thank you again for your dedication toward the James project.

One very last thing: I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Thanks again,

Cheers,

Benoit

**Pull request merged**
