### PR TITLE
Update log4j to 2.16.0

### PR DESCRIPTION
**Pull request by quantranhong1999**

### CODE REVIEW

**Comment by mbaechler** [comment]
I disagree with this fix: a lib should never come with a logger implementation but rely on slf4j instead.
If a dependency requires log4j, then use log4j-to-slf4j to break this dependency

**Comment by chibenwa** [comment]
@mbaechler the scope of use is `test`. Your remark is likely not applicable...

**Comment by mbaechler** [comment]
Well, the CVE is not applicable neither then, is it?

**Comment by chibenwa** [comment]
True but the upgrade do not hurt.

**Review by mbaechler — APPROVED** [review]
please just change the message and we will be good

**Comment by chibenwa** [comment]
(reworded upon merge)

**Pull request merged**
